const Images = {
	categoryAccessory: require('./category-images/accessories.jfif'),
	categoryCloth: require('./category-images/cloth.jfif'),
    categoryDesign: require('./category-images/design.jfif'),
    categoryMachine: require('./category-images/machine.jfif'),
    categoryTools: require('./category-images/tools.png'),

    landingPageImage: require('./design.jfif'),

    product1: require('./product-images/clothing (1).jfif'),
    product2: require('./product-images/clothing (2).jfif'),
    product3: require('./product-images/clothing (3).jfif'),
    product4: require('./product-images/clothing (4).jfif'),
    product5: require('./product-images/clothing (5).jfif'),
    product6: require('./product-images/clothing (1).png'),
    product7: require('./product-images/clothing (6).jfif'),
    product8: require('./product-images/clothing (7).jfif'),

    product9: require('./product-images/setofthreads.jpg'),
    product10: require('./product-images/setofthreads1.png'),
    product11: require('./product-images/setofthreads2.png'),
    product12: require('./product-images/hoop.png'),
    product13: require('./product-images/hoop1.jpg'),
    product14: require('./product-images/threadnipper.jpg'),
    product15: require('./product-images/seamripper.jpg'),
    product16: require('./product-images/pincushion.jpg'),
    product17: require('./product-images/punchneedle.jpg'),
    product18: require('./product-images/crewelneedle.jpg'),

    product19: require('./product-images/acc1.jpg'),
    product20: require('./product-images/acc2.png'),
    product21: require('./product-images/acc3.jpg'),
    product22: require('./product-images/acc4.jpg'),
    product23: require('./product-images/acc5.jpg'),
    product24: require('./product-images/acc6.jpg'),
    product25: require('./product-images/acc7.jpg'),
    product26: require('./product-images/acc8.jpg'),

    product27: require('./product-images/des1.jpg'),
    product28: require('./product-images/des2.jpg'),
    product29: require('./product-images/des3.jpg'),
    product30: require('./product-images/des4.jpg'),
    product31: require('./product-images/des5.jpg'),
    product32: require('./product-images/des6.jpg'),
    product33: require('./product-images/des7.jpg'),
    product34: require('./product-images/des8.jpg'),

    product35: require('./product-images/mac1.jpg'),
    product36: require('./product-images/mac2.jpg'),
    product37: require('./product-images/mac3.jpg'),
    product38: require('./product-images/mac4.jpg'),
    product39: require('./product-images/mac5.jpg'),
    product40: require('./product-images/mac6.jpg'),
    product41: require('./product-images/mac7.jpg'),
    product42: require('./product-images/mac8.jpg'),
};

export default Images;