import { v4 as uuid } from "uuid";
import Images from "../../asset/image";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Women's Cotton Shirt",
    brand: "Akriti",
    image: Images.product1,
    price: "1700",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Women's Jeans",
    brand: "Non Stop",
    image: Images.product2,
    price: "2000",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.4",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Smiling Shirt",
    brand: "Red",
    image: Images.product3,
    price: "700",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Women's Shirt",
    brand: "Mango",
    image: Images.product4,
    price: "1100",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.0",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Women's T-Shirt",
    brand: "Giffrae",
    image: Images.product5,
    price: "500",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.7",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Beige Crop Top",
    brand: "Frills",
    image: Images.product6,
    price: "950",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Women's Shirt",
    brand: "Mango",
    image: Images.product7,
    price: "800",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.1",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Women's Formal Shirt",
    brand: "Colors",
    image: Images.product8,
    price: "3500",
    onSale: true,
    salePrice: "1500",    
    outOfStock: false,
    rating: "4.5",
    categoryName: "Clothing"
  },
  {
    _id: uuid(),
    title: "Set of 7 Threads",
    brand: "DMC",
    image: Images.product9,
    price: "300",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.2",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Set of 12 Threads",
    brand: "DMC",
    image: Images.product10,
    price: "700",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.5",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Embroidery Thread Size 8",
    brand: "Valdani",
    image: Images.product11,
    price: "1000",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.8",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Single Hoop",
    brand: "SD",
    image: Images.product12,
    price: "100",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Set of Hoops",
    brand: "SD",
    image: Images.product13,
    price: "500",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Thread Nipper",
    brand: "Praniti",
    image: Images.product14,
    price: "1700",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Seam Ripper",
    brand: "Praniti",
    image: Images.product15,
    price: "150",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.9",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Pin Cushion",
    brand: "Crafty",
    image: Images.product16,
    price: "90",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.0",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Punch Needle",
    brand: "Blooms",
    image: Images.product17,
    price: "1700",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.1",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Crewel Needle",
    brand: "Colonial",
    image: Images.product18,
    price: "95",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.5",
    categoryName: "Tools"
  },
  {
    _id: uuid(),
    title: "Yellow Embroidery Linen Floral Bow Head Band",
    brand: "The Littleish",
    image: Images.product19,
    price: "170",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.3",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "Set of Embroidered Buttons",
    brand: "Forever",
    image: Images.product20,
    price: "500",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.9",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "Embroidered Purple Cap",
    brand: "Actions",
    image: Images.product21,
    price: "2700",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.6",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "Teal Potli",
    brand: "Shichan",
    image: Images.product22,
    price: "3500",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.9",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "Necklace Pendant",
    brand: "Anu",
    image: Images.product23,
    price: "1200",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.1",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "Velet Scrunchies",
    brand: "The Littleish",
    image: Images.product24,
    price: "200",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.2",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "Floral KeyChain",
    brand: "Anu",
    image: Images.product25,
    price: "850",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.5",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "M Letter Tote Bag",
    brand: "Bagee",
    image: Images.product26,
    price: "1300",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Accessories"
  },
  {
    _id: uuid(),
    title: "Pink Roses Bouquet",
    brand: "Aanchal",
    image: Images.product27,
    price: "100",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.1",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "Lemonade",
    brand: "Aanchal",
    image: Images.product28,
    price: "200",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.3",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "Icy Winter Wreath",
    brand: "Aanchal",
    image: Images.product29,
    price: "500",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.7",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "Keep It Cosy",
    brand: "Aanchal",
    image: Images.product30,
    price: "300",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "3.3",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "Spring Hydrangea",
    brand: "Aanchal",
    image: Images.product31,
    price: "700",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.3",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "Love Is Love",
    brand: "Aanchal",
    image: Images.product32,
    price: "400",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.3",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "Flower Mandala",
    brand: "Aanchal",
    image: Images.product33,
    price: "900",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.9",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "Folk Bird",
    brand: "Aanchal",
    image: Images.product34,
    price: "1300",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.9",
    categoryName: "Designs"
  },
  {
    _id: uuid(),
    title: "BP3600",
    brand: "Brother",
    image: Images.product35,
    price: "2,95,000",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.5",
    categoryName: "Embroidery Machines"
  },
  {
    _id: uuid(),
    title: "INNOV-IS V3 SE",
    brand: "Brother",
    image: Images.product36,
    price: "2,35,000",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Embroidery Machines"
  },
  {
    _id: uuid(),
    title: "Innov-is F440E",
    brand: "Brother",
    image: Images.product37,
    price: "95,000",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Embroidery Machines"
  },
  {
    _id: uuid(),
    title: "INNOV-IS V5",
    brand: "Brother",
    image: Images.product38,
    price: "2,85,000",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Embroidery Machines"
  },
  {
    _id: uuid(),
    title: "Janome",
    brand: "Usha",
    image: Images.product39,
    price: "17,500",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Embroidery Machines"
  },
  {
    _id: uuid(),
    title: "Handy Stitch Machine",
    brand: "SAUM ",
    image: Images.product40,
    price: "900",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Embroidery Machines"
  },
  {
    _id: uuid(),
    title: "Sew & Go",
    brand: "Bernette",
    image: Images.product41,
    price: "14,850",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Embroidery Machines"
  },
  {
    _id: uuid(),
    title: "Janome Excella DLX",
    brand: "Usha",
    image: Images.product42,
    price: "13,900",
    onSale: false,
    salePrice: "0",    
    outOfStock: false,
    rating: "4.0",
    categoryName: "Embroidery Machines"
  }
];